name: Linters and Node Modules Checker

on: pull_request

jobs:
  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: |
          npm install
      - name: Run ESlint
        run: |
          npm run lint
  node-modules-check:
    name: Node Modules Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Node Modules
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
